### ISSUE TITLE
some content is missing in the wiki

### ISSUE THREAD

**Issue by dtsw** [modelglue/modelglue-framework#9]
For example in https://github.com/modelglue/modelglue-framework/wiki/Section-4, Exercise: Request Format, 3.: "... and find . Add a  ...". I tried to do the Exercise w/o success.

**Comment by sipacate** [comment]
OK. I fixed it. There was some formatting that got lost in the switch 
from Trac to Github.

https://github.com/modelglue/modelglue-framework/wiki/Section-4

Let me know if you have any more issues.

DW

dtsw wrote:

**Comment by dtsw** [comment]
Oh cool thx. Yeah in section 3 "Exercise: Dealing with Data", but less important, it is sometimes referring to "the section" only, but which one is actually easy to find out, so no big deal.

**Comment by sipacate** [comment]
Ok. Those are also fixed. Thanks for letting me know.

https://github.com/modelglue/modelglue-framework/wiki/Section-3
